# Generated by Django 4.0 on 2022-04-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_mazmuni_alter_post_nomi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Arxiv', 'verbose_name_plural': 'Arxivlar'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='mazmuni',
        ),
        migrations.AddField(
            model_name='post',
            name='yillar',
            field=models.IntegerField(default=-33),
            preserve_default=False,
        ),
    ]
